// Auto-generated by scripts/discover-backend-plugins.js
// DO NOT EDIT MANUALLY

#[path = "../../../../plugins/database/mod.rs"]
pub mod database;
#[path = "../../../../plugins/system/mod.rs"]
pub mod system;

use crate::bridge::core::plugin_manager::PluginManager;

/// Auto-generated plugin registration function
pub fn register_all_plugins(manager: &mut PluginManager) {
    log::info!("📦 Registering 2 auto-discovered plugins...");

    // Tier 0: Core plugins
    manager.register(database::DatabasePlugin);

    // Tier 3+: Other plugins
    manager.register(system::SystemPlugin);

    log::info!("✅ Plugin registration complete (2 plugins)");
}
