pub mod events;
pub mod services;
pub mod plugin;
pub mod plugin_context;
pub mod plugin_manager;
pub mod websocket_bridge;
pub mod plugin_router;
pub mod router_utils;
pub mod plugin_macros;
pub mod dynamic_plugin_loader;
pub mod plugin_exports;

pub use events::{Event, EventBus};
pub use services::ServiceRegistry;
pub use plugin::{Plugin, PluginMetadata};
pub use plugin_context::PluginContext;
pub use plugin_manager::PluginManager;
pub use websocket_bridge::WebSocketBridge;
pub use plugin_router::{PluginRouter, RouterRegistry};
pub use router_utils::*;
pub use dynamic_plugin_loader::{DynamicPluginLoader, PluginInfo};
